#!/bin/bash

read url
value=`curl -s -o /dev/null -w "%{http_code}" $url | cut -c1`
#curl -s -o /dev/null -w "%{http_code}" $url


if [ $value == "2" ]
then
	echo "HTTP status is 1xx"
	exit 0

elif [ $value == "3" ]
then 
	echo "HTTP status is 3xx"
	exit 1

elif [ $value = "5" ] 
then
	echo "HTTP status is 5xx"
	exit 2

else 
	exit 3

fi
